version: '3.9'

services:
  db:
    image: postgres:15
    container_name: user_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
